package com.xiyue.creator.api.BlockEntities.StrainerFrameEntity;

import com.xiyue.creator.MyEnum.DustType;
import com.xiyue.creator.tag.BiomeTag;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.biome.Biome;

import java.util.*;

import static com.xiyue.creator.MyEnum.DustType.*;

public class BiomeDustMap {
    public record WeightedDust(DustType type, int weight) {}
    private static final Map<TagKey<Biome>, List<WeightedDust>> WATER_BIOME_MAP = new HashMap<>();
    private static final Map<TagKey<Biome>, List<WeightedDust>> LAVA_BIOME_MAP = new HashMap<>();

    static {
        //水
        //默认矿物组
        registerWaterBiomeMap(null,
                weight(TINY_DUST_CLAY,600),
                weight(TINY_DUST_STONE,600),
                weight(TINY_DUST_SAND,600),
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁矿
                weight(TINY_IMPURE_DUST_MAGNETITE,40),//磁铁
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,20),//黄铜
                weight(TINY_IMPURE_DUST_CASSITERITE,25),//锡石
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,25),//锡石砂
                weight(TINY_IMPURE_DUST_REDSTONE,15)//红石
        );
        //群系矿物组
        //平原
        registerWaterBiomeMap(BiomeTag.IS_PLAIN,
                weight(TINY_DUST_CLAY,240),
                weight(TINY_DUST_STONE,360),
                weight(TINY_DUST_SAND,180),
                weight(SMALL_DUST_STONE,300),
                weight(TINY_IMPURE_DUST_HEMATITE,100),//赤铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE,80),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,80),//孔雀石
                weight(TINY_IMPURE_DUST_REDSTONE,60),//红石
                weight(TINY_IMPURE_DUST_SALT,20),//盐
                weight(TINY_IMPURE_DUST_GOLD,1)//金
        );
        //樱花林
        registerWaterBiomeMap(BiomeTag.IS_CHERRY_GROVE,
                weight(DUST_CLAY,400),
                weight(SMALL_DUST_STONE,300),
                weight(TINY_DUST_SAND,400),
                weight(TINY_IMPURE_DUST_YELLOW_LIMONITE,80),//黄褐铁
                weight(TINY_IMPURE_DUST_CASSITERITE,70),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,60),//孔雀石
                weight(TINY_IMPURE_DUST_APATITE,20),//磷
                weight(TINY_IMPURE_DUST_SILVER,3),//银
                weight(TINY_IMPURE_DUST_REDSTONE,10)//红石
        );
        //沙漠
        registerWaterBiomeMap(BiomeTag.IS_DESERT,
                weight(TINY_DUST_SAND,450),
                weight(SMALL_DUST_SAND,400),
                weight(DUST_SAND,250),
                weight(TINY_IMPURE_DUST_MAGNETITE,40),//磁铁矿
                weight(TINY_IMPURE_DUST_HEMATITE,30),//赤铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,60),//锡石砂
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,35),//黄铜
                weight(TINY_IMPURE_DUST_REDSTONE,10),//红石
                weight(TINY_IMPURE_DUST_GOLD,2),//金
                weight(TINY_IMPURE_DUST_PLATINUM,1),//铂
                weight(TINY_IMPURE_DUST_SILVER,3)//银
        );
        //黑深林
        registerWaterBiomeMap(BiomeTag.IS_DARK_FOREST,
                weight(SMALL_DUST_CLAY,400),
                weight(SMALL_DUST_STONE,300),
                weight(DUST_SAND,250),
                weight(TINY_IMPURE_DUST_HEMATITE,60),//赤铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE,50),//锡石
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,40),//黄铜
                weight(TINY_IMPURE_DUST_COPPER,20),//铜
                weight(TINY_IMPURE_DUST_REDSTONE,30),//红石
                weight(TINY_IMPURE_DUST_GALENA,30),//方铅
                weight(TINY_IMPURE_DUST_GRAPHITE,3),//石墨
                weight(TINY_IMPURE_DUST_COAL,20)//碳
        );
        //恶地
        registerWaterBiomeMap(BiomeTag.IS_BADLANDS,
                weight(TINY_DUST_CLAY,600),
                weight(SMALL_DUST_CLAY,400),
                weight(DUST_CLAY,300),
                weight(TINY_IMPURE_DUST_YELLOW_LIMONITE,20),//褐铁矿
                weight(TINY_IMPURE_DUST_PYRITE,20),//黄铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,20),//锡石砂
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_REDSTONE,1),//红石
                weight(TINY_IMPURE_DUST_GOLD,10),//金
                weight(TINY_IMPURE_DUST_SULFUR,15),//硫磺
                weight(TINY_IMPURE_DUST_GYPSUM,20)//石膏
        );
        //巨型针叶林
        registerWaterBiomeMap(BiomeTag.IS_GIANT_TREE_TAIGA,
                weight(TINY_DUST_CLAY,600),
                weight(SMALL_DUST_CLAY,500),
                weight(SMALL_DUST_STONE,300),
                weight(TINY_IMPURE_DUST_PYRITE,20),//黄铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE,15),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_SPHALERITE,20),//闪锌
                weight(TINY_IMPURE_DUST_REDSTONE,10),//红石
                weight(TINY_IMPURE_DUST_SPODUMENE,5),//锂辉石
                weight(TINY_IMPURE_DUST_COAL,15),//煤
                weight(TINY_IMPURE_DUST_GRAPHITE,3)//石墨
        );
        //丛林
        registerWaterBiomeMap(BiomeTag.IS_JUNGLE,
                weight(TINY_DUST_CLAY,400),
                weight(SMALL_DUST_CLAY,500),
                weight(SMALL_DUST_SAND,500),
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,60),//黄铜
                weight(TINY_IMPURE_DUST_CASSITERITE,50),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁矿
                weight(TINY_IMPURE_DUST_BAUXITE,15),//铝土
                weight(TINY_IMPURE_DUST_REDSTONE,15),//红石
                weight(TINY_IMPURE_DUST_COAL,20),//煤
                weight(TINY_IMPURE_DUST_APATITE,5)//磷灰石
        );
        //积雪针叶林
        registerWaterBiomeMap(BiomeTag.IS_SNOWY_TAIGA,
                weight(TINY_DUST_STONE,500),
                weight(SMALL_DUST_STONE,400),
                weight(DUST_STONE,300),
                weight(SMALL_DUST_SAND,100),
                weight(TINY_IMPURE_DUST_COPPER,10),//铜
                weight(TINY_IMPURE_DUST_BORNITE,30),//斑铜
                weight(TINY_IMPURE_DUST_CASSITERITE,40),//锡石
                weight(TINY_IMPURE_DUST_PENTLANDITE,50),//镍黄铁
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_PLATINUM,2),//铂
                weight(TINY_IMPURE_DUST_CALCITE,15)//方解石
        );
        //热带草原
        registerWaterBiomeMap(BiomeTag.IS_SAVANNA,
                weight(TINY_DUST_SAND,600),
                weight(SMALL_DUST_SAND,500),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_IMPURE_DUST_CASSITERITE,30),//锡石
                weight(TINY_IMPURE_DUST_CHALCOCITE,20),//辉铜
                weight(TINY_IMPURE_DUST_HEMATITE,60),//赤铁
                weight(TINY_IMPURE_DUST_MAGNESITE,30),//菱镁矿
                weight(TINY_IMPURE_DUST_ROCK_SALT,10),//盐岩
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_SULFUR,20),//硫
                weight(TINY_IMPURE_DUST_BERYL,8)//绿柱石
        );
        //山地
        registerWaterBiomeMap(BiomeTag.IS_MOUNTAIN,
                weight(TINY_DUST_STONE,700),
                weight(TINY_DUST_SAND,200),
                weight(SMALL_DUST_STONE,600),
                weight(DUST_STONE,600),
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,25),//锡石
                weight(TINY_IMPURE_DUST_CHALCOCITE,30),//辉铜
                weight(TINY_IMPURE_DUST_PYRITE,30),//黄铁
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁
                weight(TINY_IMPURE_DUST_CHROMITE,10),//铬铁
                weight(TINY_IMPURE_DUST_ROCK_SALT,10),//盐岩
                weight(TINY_IMPURE_DUST_REDSTONE,15),//红石
                weight(TINY_IMPURE_DUST_REALGAR,20),//雄黄
                weight(TINY_IMPURE_DUST_LAPIS,15)//雄黄
        );
        //沙滩
        registerWaterBiomeMap(BiomeTag.IS_BEACH,
                weight(TINY_DUST_SAND,500),
                weight(SMALL_DUST_SAND,400),
                weight(DUST_SAND,400),
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,60),//锡石砂
                weight(TINY_IMPURE_DUST_CHALCOCITE,60),//辉铜
                weight(TINY_IMPURE_DUST_MAGNETITE,80),//磁铁
                weight(TINY_IMPURE_DUST_SALT,40),//盐
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_SODALITE,20),//方钠
                weight(TINY_IMPURE_DUST_GLAUCONITE_SAND,20),//海绿石砂
                weight(TINY_IMPURE_DUST_TALC,20)//滑石
        );
        //河流
        registerWaterBiomeMap(BiomeTag.IS_RIVER,
                weight(TINY_DUST_SAND,500),
                weight(TINY_DUST_CLAY,600),
                weight(TINY_DUST_STONE,300),
                weight(TINY_IMPURE_DUST_CASSITERITE,60),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,40),//孔雀石
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,30),//黄铜
                weight(TINY_IMPURE_DUST_MAGNETITE,80),//磁铁
                weight(TINY_IMPURE_DUST_REDSTONE,30),//红石
                weight(TINY_IMPURE_DUST_CINNABAR,20),//朱砂
                weight(TINY_IMPURE_DUST_DIATOMITE,10)//硅藻
        );
        //桦木林
        registerWaterBiomeMap(BiomeTag.IS_BIRCH_FOREST,
                weight(TINY_DUST_CLAY,400),
                weight(TINY_DUST_STONE,500),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_IMPURE_DUST_CASSITERITE,40),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,50),//孔雀石
                weight(TINY_IMPURE_DUST_PENTLANDITE,30),//镍黄铁
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁
                weight(TINY_IMPURE_DUST_GRAPHITE,3),//石墨
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_COAL,10)//煤
        );
        //森林
        registerWaterBiomeMap(BiomeTag.IS_FOREST,
                weight(TINY_DUST_CLAY,300),
                weight(TINY_DUST_STONE,500),
                weight(SMALL_DUST_STONE,400),
                weight(TINY_IMPURE_DUST_CASSITERITE,40),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,50),//孔雀石
                weight(TINY_IMPURE_DUST_CHALCOCITE,10),//辉铜
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁
                weight(TINY_IMPURE_DUST_SPHALERITE,20),//闪锌
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_COAL,15),//煤
                weight(TINY_IMPURE_DUST_COBALTITE,10)//辉钴
        );
        //针叶林
        registerWaterBiomeMap(BiomeTag.IS_TAIGA,
                weight(TINY_DUST_CLAY,300),
                weight(DUST_STONE,400),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_IMPURE_DUST_CASSITERITE,40),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,60),//孔雀石
                weight(TINY_IMPURE_DUST_PYRITE,50),//黄铁
                weight(TINY_IMPURE_DUST_SULFUR,30),//硫
                weight(TINY_IMPURE_DUST_SPHALERITE,35),//闪锌
                weight(TINY_IMPURE_DUST_REDSTONE,15),//红石
                weight(TINY_IMPURE_DUST_GALENA,20),//方铅
                weight(TINY_IMPURE_DUST_COAL,10)//煤
        );
        //沼泽
        registerWaterBiomeMap(BiomeTag.IS_SWAMP,
                weight(TINY_DUST_CLAY,500),
                weight(SMALL_DUST_CLAY,400),
                weight(DUST_CLAY,200),
                weight(TINY_IMPURE_DUST_CASSITERITE,25),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_PYRITE,60),//黄铁
                weight(TINY_IMPURE_DUST_REDSTONE,30),//红石
                weight(TINY_IMPURE_DUST_GALENA,25),//方铅
                weight(TINY_IMPURE_DUST_SULFUR,20),//硫
                weight(TINY_IMPURE_DUST_REALGAR,15)//雄黄
        );
        //蘑菇岛
        registerWaterBiomeMap(BiomeTag.IS_MUSHROOM_FIELD,
                weight(DUST_SAND,500),
                weight(TINY_DUST_CLAY,200),
                weight(DUST_CLAY,500),
                weight(TINY_IMPURE_DUST_CASSITERITE,25),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_MAGNETITE,60),//磁铁
                weight(TINY_IMPURE_DUST_REDSTONE,40),//红石
                weight(TINY_IMPURE_DUST_LAPIS,15),//青金石
                weight(TINY_IMPURE_DUST_EMERALD,10),//绿宝石
                weight(TINY_IMPURE_DUST_SILVER,8),//银
                weight(TINY_IMPURE_DUST_PLATINUM,5),//铂
                weight(TINY_IMPURE_DUST_GOLD,6)//金
        );
        //雪原
        registerWaterBiomeMap(BiomeTag.IS_SNOWY_PLAIN,
                weight(TINY_DUST_SAND,300),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_DUST_STONE,400),
                weight(TINY_IMPURE_DUST_CASSITERITE,30),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,40),//孔雀石
                weight(TINY_IMPURE_DUST_MAGNETITE,50),//磁铁
                weight(TINY_IMPURE_DUST_ILMENITE,20),//钛铁
                weight(TINY_IMPURE_DUST_CALCITE,35),//方解石
                weight(TINY_IMPURE_DUST_REDSTONE,30),//红石
                weight(TINY_IMPURE_DUST_PLATINUM,3)//铂
        );
        //海洋
        registerWaterBiomeMap(BiomeTag.IS_OCEAN,
                weight(TINY_DUST_SAND,300),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_DUST_STONE,400),
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,30),//锡石砂
                weight(TINY_IMPURE_DUST_MALACHITE,20),//孔雀石
                weight(TINY_IMPURE_DUST_COPPER,10),//铜
                weight(TINY_IMPURE_DUST_MAGNETITE,20),//磁铁
                weight(TINY_IMPURE_DUST_REDSTONE,10),//红石
                weight(TINY_IMPURE_DUST_SPHALERITE,15),//闪锌
                weight(TINY_IMPURE_DUST_DIATOMITE,40),//硅藻
                weight(TINY_IMPURE_DUST_TALC,35),//滑石
                weight(TINY_IMPURE_DUST_SOAPSTONE,20),//皂石
                weight(TINY_IMPURE_DUST_SALT,50),//盐
                weight(TINY_IMPURE_DUST_PYROLUSITE,10),//软锰
                weight(TINY_IMPURE_DUST_MAGNESITE,10)//菱镁
        );











        //岩浆
        //默认矿物组
        registerLavaBiomeMap(null,
                weight(TINY_DUST_CLAY,600),
                weight(TINY_DUST_STONE,600),
                weight(TINY_DUST_SAND,600),
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁矿
                weight(TINY_IMPURE_DUST_MAGNETITE,40),//磁铁
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,20),//黄铜
                weight(TINY_IMPURE_DUST_CASSITERITE,25),//锡石
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,25),//锡石砂
                weight(TINY_IMPURE_DUST_REDSTONE,15)//红石
        );
        //群系矿物组
        //平原
        registerLavaBiomeMap(BiomeTag.IS_PLAIN,
                weight(TINY_DUST_CLAY,240),
                weight(TINY_DUST_STONE,360),
                weight(TINY_DUST_SAND,180),
                weight(SMALL_DUST_STONE,300),
                weight(TINY_IMPURE_DUST_HEMATITE,100),//赤铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE,80),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,80),//孔雀石
                weight(TINY_IMPURE_DUST_REDSTONE,60),//红石
                weight(TINY_IMPURE_DUST_SALT,20),//盐
                weight(TINY_IMPURE_DUST_GOLD,1)//金
        );
        //樱花林
        registerLavaBiomeMap(BiomeTag.IS_CHERRY_GROVE,
                weight(DUST_CLAY,400),
                weight(SMALL_DUST_STONE,300),
                weight(TINY_DUST_SAND,400),
                weight(TINY_IMPURE_DUST_YELLOW_LIMONITE,80),//黄褐铁
                weight(TINY_IMPURE_DUST_CASSITERITE,70),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,60),//孔雀石
                weight(TINY_IMPURE_DUST_APATITE,20),//磷
                weight(TINY_IMPURE_DUST_SILVER,3),//银
                weight(TINY_IMPURE_DUST_REDSTONE,10)//红石
        );
        //沙漠
        registerLavaBiomeMap(BiomeTag.IS_DESERT,
                weight(TINY_DUST_SAND,450),
                weight(SMALL_DUST_SAND,400),
                weight(DUST_SAND,250),
                weight(TINY_IMPURE_DUST_MAGNETITE,40),//磁铁矿
                weight(TINY_IMPURE_DUST_HEMATITE,30),//赤铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,60),//锡石砂
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,35),//黄铜
                weight(TINY_IMPURE_DUST_REDSTONE,10),//红石
                weight(TINY_IMPURE_DUST_GOLD,2),//金
                weight(TINY_IMPURE_DUST_PLATINUM,1),//铂
                weight(TINY_IMPURE_DUST_SILVER,3)//银
        );
        //黑深林
        registerLavaBiomeMap(BiomeTag.IS_DARK_FOREST,
                weight(SMALL_DUST_CLAY,400),
                weight(SMALL_DUST_STONE,300),
                weight(DUST_SAND,250),
                weight(TINY_IMPURE_DUST_HEMATITE,60),//赤铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE,50),//锡石
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,40),//黄铜
                weight(TINY_IMPURE_DUST_COPPER,20),//铜
                weight(TINY_IMPURE_DUST_REDSTONE,30),//红石
                weight(TINY_IMPURE_DUST_GALENA,30),//方铅
                weight(TINY_IMPURE_DUST_GRAPHITE,3),//石墨
                weight(TINY_IMPURE_DUST_COAL,20)//碳
        );
        //恶地
        registerLavaBiomeMap(BiomeTag.IS_BADLANDS,
                weight(TINY_DUST_CLAY,600),
                weight(SMALL_DUST_CLAY,400),
                weight(DUST_CLAY,300),
                weight(TINY_IMPURE_DUST_YELLOW_LIMONITE,20),//褐铁矿
                weight(TINY_IMPURE_DUST_PYRITE,20),//黄铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,20),//锡石砂
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_REDSTONE,1),//红石
                weight(TINY_IMPURE_DUST_GOLD,10),//金
                weight(TINY_IMPURE_DUST_SULFUR,15),//硫磺
                weight(TINY_IMPURE_DUST_GYPSUM,20)//石膏
        );
        //巨型针叶林
        registerLavaBiomeMap(BiomeTag.IS_GIANT_TREE_TAIGA,
                weight(TINY_DUST_CLAY,600),
                weight(SMALL_DUST_CLAY,500),
                weight(SMALL_DUST_STONE,300),
                weight(TINY_IMPURE_DUST_PYRITE,20),//黄铁矿
                weight(TINY_IMPURE_DUST_CASSITERITE,15),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_SPHALERITE,20),//闪锌
                weight(TINY_IMPURE_DUST_REDSTONE,10),//红石
                weight(TINY_IMPURE_DUST_SPODUMENE,5),//锂辉石
                weight(TINY_IMPURE_DUST_COAL,15),//煤
                weight(TINY_IMPURE_DUST_GRAPHITE,3)//石墨
        );
        //丛林
        registerLavaBiomeMap(BiomeTag.IS_JUNGLE,
                weight(TINY_DUST_CLAY,400),
                weight(SMALL_DUST_CLAY,500),
                weight(SMALL_DUST_SAND,500),
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,60),//黄铜
                weight(TINY_IMPURE_DUST_CASSITERITE,50),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁矿
                weight(TINY_IMPURE_DUST_BAUXITE,15),//铝土
                weight(TINY_IMPURE_DUST_REDSTONE,15),//红石
                weight(TINY_IMPURE_DUST_COAL,20),//煤
                weight(TINY_IMPURE_DUST_APATITE,5)//磷灰石
        );
        //积雪针叶林
        registerLavaBiomeMap(BiomeTag.IS_SNOWY_TAIGA,
                weight(TINY_DUST_STONE,500),
                weight(SMALL_DUST_STONE,400),
                weight(DUST_STONE,300),
                weight(SMALL_DUST_SAND,100),
                weight(TINY_IMPURE_DUST_COPPER,10),//铜
                weight(TINY_IMPURE_DUST_BORNITE,30),//斑铜
                weight(TINY_IMPURE_DUST_CASSITERITE,40),//锡石
                weight(TINY_IMPURE_DUST_PENTLANDITE,50),//镍黄铁
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_PLATINUM,2),//铂
                weight(TINY_IMPURE_DUST_CALCITE,15)//方解石
        );
        //热带草原
        registerLavaBiomeMap(BiomeTag.IS_SAVANNA,
                weight(TINY_DUST_SAND,600),
                weight(SMALL_DUST_SAND,500),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_IMPURE_DUST_CASSITERITE,30),//锡石
                weight(TINY_IMPURE_DUST_CHALCOCITE,20),//辉铜
                weight(TINY_IMPURE_DUST_HEMATITE,60),//赤铁
                weight(TINY_IMPURE_DUST_MAGNESITE,30),//菱镁矿
                weight(TINY_IMPURE_DUST_ROCK_SALT,10),//盐岩
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_SULFUR,20),//硫
                weight(TINY_IMPURE_DUST_BERYL,8)//绿柱石
        );
        //山地
        registerLavaBiomeMap(BiomeTag.IS_MOUNTAIN,
                weight(TINY_DUST_STONE,700),
                weight(TINY_DUST_SAND,200),
                weight(SMALL_DUST_STONE,600),
                weight(DUST_STONE,600),
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,25),//锡石
                weight(TINY_IMPURE_DUST_CHALCOCITE,30),//辉铜
                weight(TINY_IMPURE_DUST_PYRITE,30),//黄铁
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁
                weight(TINY_IMPURE_DUST_CHROMITE,10),//铬铁
                weight(TINY_IMPURE_DUST_ROCK_SALT,10),//盐岩
                weight(TINY_IMPURE_DUST_REDSTONE,15),//红石
                weight(TINY_IMPURE_DUST_REALGAR,20),//雄黄
                weight(TINY_IMPURE_DUST_LAPIS,15)//雄黄
        );
        //沙滩
        registerLavaBiomeMap(BiomeTag.IS_BEACH,
                weight(TINY_DUST_SAND,500),
                weight(SMALL_DUST_SAND,400),
                weight(DUST_SAND,400),
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,60),//锡石砂
                weight(TINY_IMPURE_DUST_CHALCOCITE,60),//辉铜
                weight(TINY_IMPURE_DUST_MAGNETITE,80),//磁铁
                weight(TINY_IMPURE_DUST_SALT,40),//盐
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_SODALITE,20),//方钠
                weight(TINY_IMPURE_DUST_GLAUCONITE_SAND,20),//海绿石砂
                weight(TINY_IMPURE_DUST_TALC,20)//滑石
        );
        //河流
        registerLavaBiomeMap(BiomeTag.IS_RIVER,
                weight(TINY_DUST_SAND,500),
                weight(TINY_DUST_CLAY,600),
                weight(TINY_DUST_STONE,300),
                weight(TINY_IMPURE_DUST_CASSITERITE,60),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,40),//孔雀石
                weight(TINY_IMPURE_DUST_CHALCOPYRITE,30),//黄铜
                weight(TINY_IMPURE_DUST_MAGNETITE,80),//磁铁
                weight(TINY_IMPURE_DUST_REDSTONE,30),//红石
                weight(TINY_IMPURE_DUST_CINNABAR,20),//朱砂
                weight(TINY_IMPURE_DUST_DIATOMITE,10)//硅藻
        );
        //桦木林
        registerLavaBiomeMap(BiomeTag.IS_BIRCH_FOREST,
                weight(TINY_DUST_CLAY,400),
                weight(TINY_DUST_STONE,500),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_IMPURE_DUST_CASSITERITE,40),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,50),//孔雀石
                weight(TINY_IMPURE_DUST_PENTLANDITE,30),//镍黄铁
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁
                weight(TINY_IMPURE_DUST_GRAPHITE,3),//石墨
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_COAL,10)//煤
        );
        //森林
        registerLavaBiomeMap(BiomeTag.IS_FOREST,
                weight(TINY_DUST_CLAY,300),
                weight(TINY_DUST_STONE,500),
                weight(SMALL_DUST_STONE,400),
                weight(TINY_IMPURE_DUST_CASSITERITE,40),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,50),//孔雀石
                weight(TINY_IMPURE_DUST_CHALCOCITE,10),//辉铜
                weight(TINY_IMPURE_DUST_HEMATITE,40),//赤铁
                weight(TINY_IMPURE_DUST_SPHALERITE,20),//闪锌
                weight(TINY_IMPURE_DUST_REDSTONE,20),//红石
                weight(TINY_IMPURE_DUST_COAL,15),//煤
                weight(TINY_IMPURE_DUST_COBALTITE,10)//辉钴
        );
        //针叶林
        registerLavaBiomeMap(BiomeTag.IS_TAIGA,
                weight(TINY_DUST_CLAY,300),
                weight(DUST_STONE,400),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_IMPURE_DUST_CASSITERITE,40),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,60),//孔雀石
                weight(TINY_IMPURE_DUST_PYRITE,50),//黄铁
                weight(TINY_IMPURE_DUST_SULFUR,30),//硫
                weight(TINY_IMPURE_DUST_SPHALERITE,35),//闪锌
                weight(TINY_IMPURE_DUST_REDSTONE,15),//红石
                weight(TINY_IMPURE_DUST_GALENA,20),//方铅
                weight(TINY_IMPURE_DUST_COAL,10)//煤
        );
        //沼泽
        registerLavaBiomeMap(BiomeTag.IS_SWAMP,
                weight(TINY_DUST_CLAY,500),
                weight(SMALL_DUST_CLAY,400),
                weight(DUST_CLAY,200),
                weight(TINY_IMPURE_DUST_CASSITERITE,25),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_PYRITE,60),//黄铁
                weight(TINY_IMPURE_DUST_REDSTONE,30),//红石
                weight(TINY_IMPURE_DUST_GALENA,25),//方铅
                weight(TINY_IMPURE_DUST_SULFUR,20),//硫
                weight(TINY_IMPURE_DUST_REALGAR,15)//雄黄
        );
        //蘑菇岛
        registerLavaBiomeMap(BiomeTag.IS_MUSHROOM_FIELD,
                weight(DUST_SAND,500),
                weight(TINY_DUST_CLAY,200),
                weight(DUST_CLAY,500),
                weight(TINY_IMPURE_DUST_CASSITERITE,25),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,30),//孔雀石
                weight(TINY_IMPURE_DUST_MAGNETITE,60),//磁铁
                weight(TINY_IMPURE_DUST_REDSTONE,40),//红石
                weight(TINY_IMPURE_DUST_LAPIS,15),//青金石
                weight(TINY_IMPURE_DUST_EMERALD,10),//绿宝石
                weight(TINY_IMPURE_DUST_SILVER,8),//银
                weight(TINY_IMPURE_DUST_PLATINUM,5),//铂
                weight(TINY_IMPURE_DUST_GOLD,6)//金
        );
        //雪原
        registerLavaBiomeMap(BiomeTag.IS_SNOWY_PLAIN,
                weight(TINY_DUST_SAND,300),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_DUST_STONE,400),
                weight(TINY_IMPURE_DUST_CASSITERITE,30),//锡石
                weight(TINY_IMPURE_DUST_MALACHITE,40),//孔雀石
                weight(TINY_IMPURE_DUST_MAGNETITE,50),//磁铁
                weight(TINY_IMPURE_DUST_ILMENITE,20),//钛铁
                weight(TINY_IMPURE_DUST_CALCITE,35),//方解石
                weight(TINY_IMPURE_DUST_REDSTONE,30),//红石
                weight(TINY_IMPURE_DUST_PLATINUM,3)//铂
        );
        //海洋
        registerLavaBiomeMap(BiomeTag.IS_OCEAN,
                weight(TINY_DUST_SAND,300),
                weight(SMALL_DUST_STONE,500),
                weight(TINY_DUST_STONE,400),
                weight(TINY_IMPURE_DUST_CASSITERITE_SAND,30),//锡石砂
                weight(TINY_IMPURE_DUST_MALACHITE,20),//孔雀石
                weight(TINY_IMPURE_DUST_COPPER,10),//铜
                weight(TINY_IMPURE_DUST_MAGNETITE,20),//磁铁
                weight(TINY_IMPURE_DUST_REDSTONE,10),//红石
                weight(TINY_IMPURE_DUST_SPHALERITE,15),//闪锌
                weight(TINY_IMPURE_DUST_DIATOMITE,40),//硅藻
                weight(TINY_IMPURE_DUST_TALC,35),//滑石
                weight(TINY_IMPURE_DUST_SOAPSTONE,20),//皂石
                weight(TINY_IMPURE_DUST_SALT,50),//盐
                weight(TINY_IMPURE_DUST_PYROLUSITE,10),//软锰
                weight(TINY_IMPURE_DUST_MAGNESITE,10)//菱镁
        );
    }

    private static WeightedDust weight(DustType type, int weight) {
        return new WeightedDust(type, weight);
    }

    private static void registerWaterBiomeMap(TagKey<Biome> biome, WeightedDust... dust) {
        WATER_BIOME_MAP.put(biome, Arrays.asList(dust));
    }

    private static void registerLavaBiomeMap(TagKey<Biome> biome, WeightedDust... dust) {
        LAVA_BIOME_MAP.put(biome, Arrays.asList(dust));
    }

    public static Map<TagKey<Biome>, List<WeightedDust>> getWaterDustForBiome(){
        return WATER_BIOME_MAP;
    }

    public static Map<TagKey<Biome>, List<WeightedDust>> getLavaDustForBiome(){
        return LAVA_BIOME_MAP;
    }

    public static String getTagName(TagKey<Biome> tag) {
        if (tag == null) return "default";
        return tag.location().getPath();
    }
}
